# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Rocket Library' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rocket Library

pod 'Firebase/Analytics'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Google'

  target 'Rocket LibraryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Rocket LibraryUITests' do
    # Pods for testing
  end

end
